name: pr-checker
on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
    branches:
      - "master"
jobs:
  check-changes:
    runs-on: ubuntu-latest
    outputs:
      reviewer: ${{ steps.filter.outputs.SELECTION }}
    steps:
      - uses: actions/checkout@v3
      - id: filter
        run: |
          SELECTION="none"
          if [[ $(git diff --name-only HEAD~1 | grep "services/" | wc -l) > 0 ]]; then
              SELECTION="services"
          fi
          if [[ $(git diff --name-only HEAD~1 | grep "application/" | wc -l) > 0 ]]; then
              SELECTION="application"
          fi
          echo "Got selection $SELECTION"
          echo "SELECTION=$SELECTION" >> $GITHUB_ENV
        shell: bash
  review-service-standards:
    runs-on: ubuntu-latest
    needs: check-changes
    if: needs.check-changes.outputs.reviewer == 'services'
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          if [ -f services/requirements.dev.txt ]; then pip install -r services/requirements.dev.txt; fi
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 ./services/ --count --select=E9,F63,F7,F82 --show-source --statistics
          # ignore max line length
          flake8 ./services/ --count --ignore=E501 --show-source --statistics
